name: Code Quality Workflow
on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master
      - development
jobs:
  publish:
    name: Linting and testing
    runs-on: ubuntu-latest
    container: node:18.17.1-alpine3.17
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install node packages
        run: pnpm install

      - name: Lint application
        run: pnpm run lint:ci

      - name: Test application
        run: pnpm run test:ci
